### ISSUE TITLE
BUG: Multiple tickers per page - adjusting duration on one impacts the other

### ISSUE THREAD

**Issue by henry74** [shivarajnaidu/ng-marquee#2]
I'm using ng-marquee in an component.  When I instantiate 2 version of the same component within a page, the duration input parameter changes the speed of the first component instead of the one it's being passed to.

**Comment by henry74** [comment]
Looks like the issue is in the ngInit() - the querySelectorAll is pulling the first instance of the tag and adjusting the duration so if you have multiple instances, the first instance is always changed, no matter what:
```javascript
    updateDuration() {
        if (!this.duration) {
            return;
        }
        this.animationElem.style.animationDuration = `${this.duration}s`;
    }
    /**
     * @return {?}
     */
    ngOnInit() {
        this.animationElem = /** @type {?} */ (document.querySelectorAll('.ng-marquee-wrapper > div')[0]);
        this.updateDuration();
    }
```

**Comment by yuvarajvemula** [comment]
Sorry for the delayed response .. I was busy with some stuff at my work .. Could you please make a pull request to backport the improvements to upstream ?

Thanks in advance @henry74

**Comment by yuvarajvemula** [comment]
@henry74 this issue is now fixed :tada:
