### ISSUE TITLE
ng-marquee refresh itself without scrolling all the text provided.

### ISSUE THREAD

**Issue by mayankdm** [shivarajnaidu/ng-marquee#3]
In my case ng-marquee behaviour for different resoutions are different.
For mobile when there are 5 to 6 marquee texts then the marquee is not completing the horizontal  scroll. The marquee is getting refreshed as soon as the first text reaches the other end due to which last text is never visible.

**Comment by berchik** [comment]
Same here, even one line of text, longer than the screen, is refreshed too early.
To fix it set the `width` to `auto` in the @media part.

**Comment by yuvarajvemula** [comment]
Sorry guys for delayed response.. Little-bit busy with other stuff.. Will try to fix asap.. Pull request will be helpful .. @berchik @mayankdm

**Comment by Hellogark** [comment]
this happens even with a simple text in one marquee, when the text reach the side of the screen it resets without scrolling the whole text

**Comment by shikkhagupta** [comment]
Its not working like original html marque component. I have one single marque with dynamic text and when I change that text the duration does not change which leads to too fast or too slow animation scrolling depending on the value of duration.
I tried giving dynamic value to duration but that is not working. It keeps a static value, the first that my component calculates and sets
Is it possible that with text length, the duration can change dynamically as well or the speed of scroll is same like in original HTML tag

**Comment by Jay-PC** [comment]
We can shed some light on this subject. It's quite easy to find the bug. We have a line of text that is maybe a normal screen width in length. Everything works fine. However, if you click the maximize window button (we are in Windows using Firefox and Edge) to un-maximize the window, grab the right side of the window frame and drag it to the left decreasing the width. When you shrink the width down to 500px two things happen... 1) the scroller jumps to a much slower crawl that is unaffected by any duration setting, and 2) the above bug starts to occur where the line scrolls half way and resets. Is it possible that you change something in the CSS when the width goes below 500px?

**Comment by Jay-PC** [comment]
I think my suspicions are correct. I found your .css file here, and you are changing some things at 500px. A couple of notes... 1) you have some redundancies you can delete, like height: 100%; and margin: 0; white-space: nowrap; ...they shouldn't actually impact anything since they are already in the base class. This leaves one new line of code (width 100%) and two modifications (transform and animation). My guess is that when it's less that 500px across, you are pushing the transform: translateX(100%); which is activating the 100% condition in the @keyframes definition, which in turn is transform: translateX(-100%); which would reset the text. Is there a way you could fix this? We will make a donation to paypal if this can work in production for us. thanks!

**Comment by Jay-PC** [comment]
actually... I think we just solved the problem on our end... in the file, ng-marquee-improved.js in the node_modules/ng-marquee-improved/fesm5 folder, we deleted "width:100%;" from Ln44, Col755 (just after the @media (max-width:500px) declaration. This fixed the problem instantly. I imagine it's likely good to do the same thing in the same file for any other file with @media setting max at 500px, so we also deleted "width:100%" in the fesm2015 folder next door at Ln35, Col751, as well as down two folders in /fesm2015/lib/ng-marquee in ng-marquee-component.js Ln34, Col751. As well as in /bundles ng-marquee-improved-umb.js  at Ln48, Col759 and ng-marquee-improved-umb-min.js at Ln1, Col1596, ng-marquee-component.js in /esm5/lib/marquee folder Ln43, Col755. Hopefully we didn't cut out a necessary value for some other browsers, but I imagine we will find that out soon enough. We can always add the value back as needed. Hopefully this helps you find the root issue.

**Comment by yuvarajvemula** [comment]
Hi @Jay-PC 

Thanks for your valuable time..

Could you please raise a pull request to fix this ?
It would be helpful. 

Thanks in advance.

**Comment by Jay-PC** [comment]
Sure. How do I do that?




=Jay


Sent from my Abacus 10+







On Thu, Feb 6, 2020 at 11:12 AM -0600, "yuvaraj" <notifications@github.com> wrote:












Hi @Jay-PC


Thanks for your valuable time..


Could you please raise a pull request to fix this ?

It would be helpful.


Thanks in advance.

**Comment by yuvarajvemula** [comment]
You can fork - then fix and create pullrequest

**Comment by yuvarajvemula** [comment]
Please try the new version and re-open the issue still if the issue persists. @mayankdm
