### ISSUE TITLE
Duplicated attribute is missing

### ISSUE THREAD

**Issue by danieljausovec** [shivarajnaidu/ng-marquee#5]
Is there any option to add new option `duplicated` like in jQuery library?
Or maybe just some hack with CSS.

Example:
https://github.com/aamirafridi/jQuery.Marquee

**Comment by yuvarajvemula** [comment]
Now there is no option...
I will look into it.. amd try to implement the same @danieljausovec 

Thank you !

**Comment by yuvarajvemula** [comment]
This feature is less likely to be implemented in this library. If we can get Pull request from outside we will add it to this @danieljausovec
